using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Lidgren.Network;
using System.Xml;

namespace Server.Classes
{
    class Player
    {
        public string Name { get; set; }    //define name property
        public string Pass { get; set; }    //define password
        public NetConnection Connection;        //define network connection
        public int X { get; set; }  //define x
        public int Y { get; set; }  //define y
        public int Map { get; set; }    //define map
        public int Direction { get; set; }  //define direction
        public int Sprite { get; set; } //define sprite
        public int Step;    //define step

        public Item MainWeapon = new Item();
        public Item OffWeapon = new Item();

        public int Level { get; set; }
        public int Health { get; set; }
        public int Hunger { get; set; }
        public int Hydration { get; set; }
        public int Experience { get; set; }
        public int Money { get; set; }
        public int Armor { get; set; }
    
        public int Strength { get; set; }
        public int Agility { get; set; }
        public int Endurance { get; set; }
        public int Stamina { get; set; }

        public Player(string name, string pass, int x, int y, int direction, int map, int level, int health, int exp, int money, int armor, int hunger, int hydration, int str, int agi, int end, int sta, NetConnection conn)
        {
            Name = name;
            Pass = pass;
            X = x;
            Y = y;
            Map = map;
            Direction = direction;
            Level = level;
            Health = health;
            Experience = exp;
            Money = money;
            Armor = armor;
            Hunger = hunger;
            Hydration = hydration;
            Strength = str;
            Agility = agi;
            Endurance = end;
            Stamina = sta;
            Connection = conn;
            MainWeapon = new Item("Gun", 1, 25, 0, (int)ItemType.RangedWeapon, 0, 0, 0, 5, 5, 5, 5);
        }

        public Player(string name, string pass, NetConnection conn)
        {
            Name = name;
            Pass = pass;
            Connection = conn;
        }

        public Player(NetConnection conn)
        {
            Connection = conn;
        }

        public Player() { }

        public void SavePlayerXML()
        {
            XmlWriterSettings userData = new XmlWriterSettings();
            userData.Indent = true;
            string sname = Name.ToLower();

            XmlWriter writer = XmlWriter.Create("Players/" + sname + ".xml", userData);
            LogWriter.WriteLog("Player XML file saved " + sname, "Server");
            writer.WriteStartDocument();
            //writer.WriteComment("This file is generated by the server.");
            writer.WriteStartElement("PlayerData");
            writer.WriteElementString("Name", Name);
            writer.WriteElementString("Password", Pass);
            writer.WriteElementString("X", X.ToString());
            writer.WriteElementString("Y", Y.ToString());
            writer.WriteElementString("Map", Map.ToString());
            writer.WriteElementString("Direction", Direction.ToString());
            writer.WriteElementString("Sprite", Sprite.ToString());
            writer.WriteElementString("Level", Level.ToString());
            writer.WriteElementString("Health", Health.ToString());
            writer.WriteElementString("Experience", Experience.ToString());
            writer.WriteElementString("Money", Money.ToString());
            writer.WriteElementString("Armor", Armor.ToString());
            writer.WriteElementString("Hunger", Hunger.ToString());
            writer.WriteElementString("Hydration", Hydration.ToString());
            writer.WriteElementString("Strength", Strength.ToString());
            writer.WriteElementString("Agility", Agility.ToString());
            writer.WriteElementString("Endurance", Endurance.ToString());
            writer.WriteElementString("Stamina", Stamina.ToString());
            writer.WriteEndElement();
            writer.WriteEndDocument();
            writer.Flush();
            writer.Close();
        }

        public void LoadPlayerXML()
        {
            string lname = Name.ToLower();
            XmlReader reader = XmlReader.Create("Players/" + lname + ".xml");
            LogWriter.WriteLog("Player XML file loaded " + lname, "Server");
            reader.ReadToFollowing("Name");
            Name = reader.ReadElementContentAsString();
            reader.ReadToFollowing("Password");
            Pass = reader.ReadElementContentAsString();
            reader.ReadToFollowing("X");
            X = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Y");
            Y = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Map");
            Map = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Direction");
            Direction = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Sprite");
            Sprite = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Level");
            Level = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Health");
            Health = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Experience");
            Experience = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Money");
            Money = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Armor");
            Armor = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Hunger");
            Hunger = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Hydration");
            Hydration = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Strength");
            Strength = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Agility");
            Agility = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Endurance");
            Endurance = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Stamina");
            Stamina = reader.ReadElementContentAsInt();
            reader.Close();
        }
    }

    public enum Directions
    {
        Down,
        Left,
        Right,
        Up,
        DownLeft,
        DownRight,
        UpLeft,
        UpRight
    }
}
