using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Lidgren.Network;
using System.Xml;

namespace Server.Classes
{
    class Player
    {
        public string Name { get; set; }    //define name property
        public string Pass { get; set; }
        public NetConnection Connection;
        public int X { get; set; }
        public int Y { get; set; }
        public int Direction { get; set; }
        public int Sprite { get; set; }
        public int Step;

        public Player(string name, string pass, int x, int y, int direction, NetConnection conn)
        {
            Name = name;
            Pass = pass;
            X = x;
            Y = y;
            Direction = direction;
            Connection = conn;
        }

        public Player(string name, string pass, NetConnection conn)
        {
            Name = name;
            Pass = pass;
            Connection = conn;
        }

        public Player(NetConnection conn)
        {
            Connection = conn;
        }

        public Player()
        {

        }

        public void SavePlayerXML()
        {
            XmlWriterSettings userData = new XmlWriterSettings();
            userData.Indent = true;
            string sname = Name.ToLower();

            XmlWriter writer = XmlWriter.Create("Players/" + sname + ".xml", userData);
            LogWriter.WriteLog("Player XML file saved " + sname, "Server");
            writer.WriteStartDocument();
            //writer.WriteComment("This file is generated by the server.");
            writer.WriteStartElement("PlayerData");
            writer.WriteElementString("Name", Name);
            writer.WriteElementString("Password", Pass);
            writer.WriteElementString("X", X.ToString());
            writer.WriteElementString("Y", Y.ToString());
            writer.WriteElementString("Direction", Direction.ToString());
            writer.WriteElementString("Sprite", Sprite.ToString());
            writer.WriteEndElement();
            writer.WriteEndDocument();
            writer.Flush();
            writer.Close();
        }

        public void LoadPlayerXML()
        {
            string lname = Name.ToLower();
            XmlReader reader = XmlReader.Create("Players/" + lname + ".xml");
            LogWriter.WriteLog("Player XML file loaded " + lname, "Server");
            reader.ReadToFollowing("Name");
            Name = reader.ReadElementContentAsString();
            reader.ReadToFollowing("Password");
            Pass = reader.ReadElementContentAsString();
            reader.ReadToFollowing("X");
            X = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Y");
            Y = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Direction");
            Direction = reader.ReadElementContentAsInt();
            reader.ReadToFollowing("Sprite");
            Sprite = reader.ReadElementContentAsInt();
            reader.Close();
        }
    }

    public enum Directions
    {
        Down,
        Left,
        Right,
        Up,
        DownLeft,
        DownRight,
        UpLeft,
        UpRight
    }
}
