/*
Created 2/2/2019 12:18AM
Creates PLAYER AMMO view in Sabertooths Database
Created by Steven M Fortune
Updated 2019-02-02 12:19:27.450
*/
CREATE VIEW [PLAYER AMMO]
AS
SELECT PLAYERS.ID,
	PLAYERS.NAME,
	PLAYERS.PISTOLAMMO,
	PLAYERS.ASSAULTAMMO,
	PLAYERS.ROCKETAMMO,
	PLAYERS.GRENADEAMMO
FROM PLAYERS