/*
Created 2019-02-15 15:23:53.010
Creates PLAYER MISC INFO view in Sabertooths Database
Created by Steven M Fortune
*/
CREATE VIEW [PLAYER MISC INFO]
AS
SELECT PLAYERS.ID,
	PLAYERS.NAME,
	PLAYERS.X,
	PLAYERS.Y,
	PLAYERS.AIMDIRECTION,
	PLAYERS.SPRITE,
	PLAYERS.LIGHTRADIUS,
	PLAYERS.ACCOUNTKEY,
	PLAYERS.ACTIVE
FROM PLAYERS