/*
Created 2019-02-15 15:23:53.010
Creates vPlayerMiscInfo view in Sabertooths Database
Created by Steven M Fortune
Updated 2019-02-27 10:53:50.457
*/
IF EXISTS(SELECT * FROM SYS.views WHERE name = 'vPlayerMiscInfo')
BEGIN
	DROP VIEW vPlayerMiscInfo
END
GO
CREATE VIEW vPlayerMiscInfo
AS
SELECT PLAYERS.ID,
	PLAYERS.NAME,
	PLAYERS.X,
	PLAYERS.Y,
	PLAYERS.AIMDIRECTION,
	PLAYERS.SPRITE,
	PLAYERS.LIGHTRADIUS,
	PLAYERS.ACCOUNTKEY,
	PLAYERS.ACTIVE
FROM PLAYERS