/*
Created 9/2/2018 5:18AM
Creates vPlayerStatInfo view in Sabertooths Database
Created by Steven M Fortune
Updated 2019-02-27 10:53:50.457
*/
IF EXISTS(SELECT * FROM SYS.views WHERE name = 'vPlayerStatInfo')
BEGIN
	DROP VIEW vPlayerStatInfo
END
GO
CREATE VIEW vPlayerStatInfo
AS
SELECT PLAYERS.ID,
	PLAYERS.NAME,
	PLAYERS.EMAILADDRESS,
	PLAYERS.LEVEL,
	PLAYERS.HEALTH,
	PLAYERS.MAXHEALTH,
	PLAYERS.EXPERIENCE,
	PLAYERS.MONEY,
	STATS.KILLS,
	STATS.POINTS,
	PLAYERS.ARMOR,
	PLAYERS.HUNGER,
	PLAYERS.HYDRATION,
	PLAYERS.STRENGTH,
	PLAYERS.AGILITY,
	PLAYERS.ENDURANCE,
	PLAYERS.STAMINA,
	PLAYERS.LASTLOGGED,
	STATS.DAYS AS DAYS_PLAYED,
	STATS.HOURS AS HOURS_PLAYED,
	STATS.MINUTES AS MINUTES_PLAYED,
	STATS.SECONDS AS SECONDS_PLAYED,
	STATS.LDAYS AS LONGEST_DAYS,
	STATS.LHOURS AS LONGEST_HOURS,
	STATS.LMINUTES AS LONGEST_MINUTES,
	STATS.LSECONDS AS LONGEST_SECONDS,
	STATS.LLDAYS AS LONGEST_LIFE_DAYS,
	STATS.LLMINUTES AS LONGEST_LIFE_MINUTES,
	STATS.LLSECONDS AS LONGEST_LIFE_SECONDS
FROM PLAYERS
JOIN STATS ON PLAYERS.NAME = STATS.NAME
