/*
Created 2019-02-18 12:42:58.543
Load chat data into database
Created by Steven M Fortune
*/
SELECT ID,
	NAME,
	STARTMESSAGE,
	INPROGRESSMESSAGE,
	COMPLETEMESSAGE,
	PREREQUISITEQUEST,
	LEVELREQUIRED,
	REQITEM1,
	REQITEM2,
	REQITEM3,
	REQITEM4,
	REQITEM5,
	REQITEMVALUE1,
	REQITEMVALUE2,
	REQITEMVALUE3,
	REQITEMVALUE4,
	REQITEMVALUE5,
	REQNPC1,
	REQNPC2,
	REQNPC3,
	REQNPCVALUE1,
	REQNPCVALUE2,
	REQNPCVALUE3,
	REWARDITEM1,
	REWARDITEM2,
	REWARDITEM3,
	REWARDITEM4,
	REWARDITEM5,
	REWARDITEMVALUE1,
	REWARDITEMVALUE2,
	REWARDITEMVALUE3,
	REWARDITEMVALUE4,
	REWARDITEMVALUE5,
	EXPERIENCE,
	MONEY,
	QUESTTPYE
FROM QUESTS
WHERE ID = @id
