/*
Created 9/2/2018 5:18AM
Creates ITEMS table in Sabertooths Database
Created by Steven M Fortune
*/

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'ITEMS')
CREATE TABLE ITEMS (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	NAME TEXT,
	SPRITE INTEGER,
	DAMAGE INTEGER,
	ARMOR INTEGER,
	TYPE INTEGER,
	ATTACKSPEED INTEGER,
	RELOADSPEED INTEGER,
	HEALTHRESTORE INTEGER,
	HUNGERRESTORE INTEGER,
	HYDRATERESTORE INTEGER,
	STRENGTH INTEGER,
	AGILITY INTEGER,
	ENDURANCE INTEGER,
	STAMINA INTEGER,
	CLIP INTEGER,
	MAXCLIP INTEGER,
	AMMOTYPE INTEGER,
	VALUE INTEGER,
	PROJ INTEGER,
	PRICE INTEGER,
	RARITY INTEGER
	)
