/*
Created 9/2/2018 5:12AM
Creates PLAYERS table in Sabertooths Database
Created by Steven M Fortune
*/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'PLAYERS')
	CREATE TABLE PLAYERS (
		ID INT IDENTITY(1, 1) PRIMARY KEY,
		NAME VARCHAR(25),
		PASSWORD VARCHAR(25),
		EMAILADDRESS VARCHAR(255),
		X INTEGER,
		Y INTEGER,
		MAP INTEGER,
		DIRECTION INTEGER,
		AIMDIRECTION INTEGER,
		SPRITE INTEGER,
		LEVEL INTEGER,
		POINTS INTEGER,
		HEALTH INTEGER,
		MAXHEALTH INTEGER,
		EXPERIENCE INTEGER,
		MONEY INTEGER,
		ARMOR INTEGER,
		HUNGER INTEGER,
		HYDRATION INTEGER,
		STRENGTH INTEGER,
		AGILITY INTEGER,
		ENDURANCE INTEGER,
		STAMINA INTEGER,
		PISTOLAMMO INTEGER,
		ASSAULTAMMO INTEGER,
		ROCKETAMMO INTEGER,
		GRENADEAMMO INTEGER,
		LIGHTRADIUS INTEGER,
		DAYS INTEGER,
		HOURS INTEGER,
		MINUTES INTEGER,
		SECONDS INTEGER,
		LDAYS INTEGER,
		LHOURS INTEGER,
		LMINUTES INTEGER,
		LSECONDS INTEGER,
		LLDAYS INTEGER,
		LLHOURS INTEGER,
		LLMINUTES INTEGER,
		LLSECONDS INTEGER,
		LASTLOGGED TEXT,
		ACCOUNTKEY VARCHAR(25),
		ACTIVE VARCHAR(1)
		)