/*
Created 2019-02-17 12:52:35.907
Creates QUESTS table in Sabertooths Database
Created by Steven M Fortune
*/
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'QUESTS')
CREATE TABLE QUESTS (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	NAME VARCHAR(25) NOT NULL,
	STARTMESSAGE VARCHAR(255) NOT NULL,
	INPROGRESSMESSAGE VARCHAR(255) NOT NULL,
	COMPLETEMESSAGE VARCHAR(255) NOT NULL,
	PREREQUISITEQUEST INTEGER,
	LEVELREQUIRED INTEGER,
	REQITEM1 INTEGER,
	REQITEM2 INTEGER,
	REQITEM3 INTEGER,
	REQITEM4 INTEGER,
	REQITEM5 INTEGER,
	REQITEMVALUE1 INTEGER,
	REQITEMVALUE2 INTEGER,
	REQITEMVALUE3 INTEGER,
	REQITEMVALUE4 INTEGER,
	REQITEMVALUE5 INTEGER,
	REQNPC1 INTEGER,
	REQNPC2 INTEGER,
	REQNPC3 INTEGER,
	REQNPCVALUE1 INTEGER,
	REQNPCVALUE2 INTEGER,
	REQNPCVALUE3 INTEGER,
	REWARDITEM1 INTEGER,
	REWARDITEM2 INTEGER,
	REWARDITEM3 INTEGER,
	REWARDITEM4 INTEGER,
	REWARDITEM5 INTEGER,
	REWARDITEMVALUE1 INTEGER,
	REWARDITEMVALUE2 INTEGER,
	REWARDITEMVALUE3 INTEGER,
	REWARDITEMVALUE4 INTEGER,
	REWARDITEMVALUE5 INTEGER,
	EXPERIENCE INTEGER,
	MONEY INTEGER,
	QUESTTPYE INTEGER
	)