/*
Created 9/2/2018 5:18AM
Creates BASIC PLAYER INFO view in Sabertooths Database
Created by Steven M Fortune
Updated 2019-01-21 14:33:00.010
*/
CREATE VIEW [BASIC PLAYER INFO]
AS
SELECT NAME,
	EMAILADDRESS,
	LEVEL,
	HEALTH,
	MAXHEALTH,
	EXPERIENCE,
	MONEY,
	ARMOR,
	HUNGER,
	HYDRATION,
	STRENGTH,
	AGILITY,
	ENDURANCE,
	STAMINA
FROM PLAYERS
