/*
Created 9/2/2018 5:18AM
Creates BANK table in Sabertooths Database
Created by Steven M Fortune
*/

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'BANK')
CREATE TABLE BANK (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	OWNER VARCHAR(25),
	SLOT INTEGER,
	NAME TEXT,
	SPRITE INTEGER,
	DAMAGE INTEGER,
	ARMOR INTEGER,
	TYPE INTEGER,
	ATTACKSPEED INTEGER,
	RELOADSPEED INTEGER,
	HEALTHRESTORE INTEGER,
	HUNGERRESTORE INTEGER,
	HYDRATERESTORE INTEGER,
	STRENGTH INTEGER,
	AGILITY INTEGER,
	ENDURANCE INTEGER,
	STAMINA INTEGER,
	CLIP INTEGER,
	MAXCLIP INTEGER,
	AMMOTYPE INTEGER,
	VALUE INTEGER,
	PROJ INTEGER,
	PRICE INTEGER,
	RARITY INTEGER
	)
