/*
Created 9/2/2018 5:18AM
Creates CHAT table in Sabertooths Database
Created by Steven M Fortune
Updated 1/5/2019 9:14PM
*/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'CHAT')
CREATE TABLE CHAT (
		ID INT IDENTITY(1, 1) PRIMARY KEY,
		NAME VARCHAR(25) NOT NULL,
		MAINMESSAGE VARCHAR(255) NOT NULL,
		OPTIONA VARCHAR(25) NOT NULL,
		OPTIONB VARCHAR(25) NOT NULL,
		OPTIONC VARCHAR(25) NOT NULL,
		OPTIOND VARCHAR(25) NOT NULL,
		NEXTCHATA INTEGER,
		NEXTCHATB INTEGER,
		NEXTCHATC INTEGER,
		NEXTCHATD INTEGER,
		SHOPNUM INTEGER,
		MISSIONNUM INTEGER,
		ITEMA INTEGER,
		ITEMB INTEGER,
		ITEMC INTEGER,
		VALA INTEGER,
		VALB INTEGER,
		VALC INTEGER,
		MONEY INTEGER,
		TYPE INTEGER
		)
