/*
Created 9/2/2018 5:18AM
Creates CHESTS table in Sabertooths Database
Created by Steven M Fortune
Updated 1/5/2019 9:18PM
*/

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'CHESTS')
CREATE TABLE CHESTS (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	NAME VARCHAR(25) NOT NULL,
	MONEY INTEGER,
	EXPERIENCE INTEGER,
	REQUIREDLEVEL INTEGER,
	TRAPLEVEL INTEGER,
	REQKEY INTEGER,
	DAMAGE INTEGER,
	NPCSPAWN INTEGER,
	SPAWNAMOUNT INTEGER,
	CHESTITEM VARBINARY(MAX)
	)
