/*
Created 9/2/2018 5:18AM
Creates MAINWEAPONS table in Sabertooths Database
Created by Steven M Fortune
*/

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'MAINWEAPONS')
CREATE TABLE MAINWEAPONS (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	OWNER VARCHAR(25),
	NAME TEXT,
	CLIP INTEGER,
	MAXCLIP INTEGER,
	SPRITE INTEGER,
	DAMAGE INTEGER,
	ARMOR INTEGER,
	TYPE INTEGER,
	ATTACKSPEED INTEGER,
	RELOADSPEED INTEGER,
	HEALTHRESTORE INTEGER,
	HUNGERRESTORE INTEGER,
	HYDRATERESTORE INTEGER,
	STRENGTH INTEGER,
	AGILITY INTEGER,
	ENDURANCE INTEGER,
	STAMINA INTEGER,
	AMMOTYPE INTEGER,
	VALUE INTEGER,
	PROJ INTEGER,
	PRICE INTEGER,
	RARITY INTEGER
	)
