/*
Created 9/2/2018 5:18AM
Creates MAPS table in Sabertooths Database
Created by Steven M Fortune
Updated 2019-02-07 14:40:57.820
*/

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Maps')
CREATE TABLE Maps (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Name TEXT,
	Revision INTEGER,
	Up INTEGER,
	Down INTEGER,
	Left_Side INTEGER,
	Right_Side INTEGER,
	Brightness INTEGER,
	Max_X INTEGER,
	Max_Y INTEGER,
	Npc VARBINARY(MAX),
	--Item VARBINARY(MAX),
	Ground VARBINARY(MAX),
	Mask VARBINARY(MAX),
	Mask_A VARBINARY(MAX),
	Fringe VARBINARY(MAX),
	Fringe_A VARBINARY(MAX)
	)
