/*
Created 9/2/2018 5:18AM
Creates MAPS table in Sabertooths Database
Created by Steven M Fortune
Updated 1/5/2019 9:23PM
*/

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'MAPS')
CREATE TABLE MAPS (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	NAME VARCHAR(25) NOT NULL,
	REVISION INTEGER,
	UP INTEGER,
	DOWN INTEGER,
	LEFTSIDE INTEGER,
	RIGHTSIDE INTEGER,
	BRIGHTNESS INTEGER,
	NPC VARBINARY(MAX),
	ITEM VARBINARY(MAX),
	GROUND VARBINARY(MAX),
	MASK VARBINARY(MAX),
	MASKA VARBINARY(MAX),
	FRINGE VARBINARY(MAX),
	FRINGEA VARBINARY(MAX)
	)
