/*
Created 9/2/2018 5:08AM
Creates NPCS table in Sabertooths Database
Created by Steven M Fortune
Updated 1/5/2019 9:23PM
*/

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'NPCS')
CREATE TABLE NPCS (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	NAME VARCHAR(25) NOT NULL,
	X INTEGER,
	Y INTEGER,
	DIRECTION INTEGER,
	SPRITE INTEGER,
	STEP INTEGER,
	OWNER INTEGER,
	BEHAVIOR INTEGER,
	SPAWNTIME INTEGER,
	HEALTH INTEGER,
	MAXHEALTH INTEGER,
	DAMAGE INTEGER,
	DESX INTEGER,
	DESY INTEGER,
	EXP INTEGER,
	MONEY INTEGER,
	RANGE INTEGER,
	SHOPNUM INTEGER,
	CHATNUM INTEGER,
	SPEED INTEGER
	)