IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Spells')
CREATE TABLE Spells (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Name TEXT,
	Level INTEGER,
	Icon INTEGER,
	Vital INTEGER,
	HPCost INTEGER,
	MPCost INTEGER,
	CoolDown INTEGER,
	CastTime INTEGER,
	Charges INTEGER,
	TotalTick INTEGER,
	TickInterval INTEGER,
	SpellType INTEGER,
	Range INTEGER,
	Animation INTEGER,
	AOE BIT,
	Distance INTEGER,
	Projectile BIT,
	Sprite INTEGER,
	SelfCast BIT,
	RenderOnTarget BIT
	)