IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'SpellBook')
CREATE TABLE SpellBook (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	PlayerID INTEGER,
	SpellNumber_1 INTEGER,
	SpellNumber_2 INTEGER,
	SpellNumber_3 INTEGER,
	SpellNumber_4 INTEGER,
	SpellNumber_5 INTEGER,
	SpellNumber_6 INTEGER,
	SpellNumber_7 INTEGER,
	SpellNumber_8 INTEGER,
	SpellNumber_9 INTEGER,
	SpellNumber_10 INTEGER,
	SpellNumber_11 INTEGER,
	SpellNumber_12 INTEGER,
	SpellNumber_13 INTEGER,
	SpellNumber_14 INTEGER,
	SpellNumber_15 INTEGER,
	SpellNumber_16 INTEGER,
	SpellNumber_17 INTEGER,
	SpellNumber_18 INTEGER,
	SpellNumber_19 INTEGER,
	SpellNumber_20 INTEGER,
	SpellNumber_21 INTEGER,
	SpellNumber_22 INTEGER,
	SpellNumber_23 INTEGER,
	SpellNumber_24 INTEGER,
	SpellNumber_25 INTEGER
	)